### ISSUE TITLE
fallback-sha is ignored

### ISSUE THREAD

**Issue by bperel** [nrwl/nx-set-shas#166] opened 2024-08-23 07:41 UTC
I get the following error when specifying `fallback-sha`: 

```
Warning: Unexpected input(s) 'fallback-sha', valid inputs are ['main-branch-name', 'set-environment-variables-for-job', 'error-on-no-successful-workflow', 'last-successful-event', 'working-directory', 'workflow-id']
```

Indeed, `fallback-sha` is never passed to the [list of envs in https://github.com/nrwl/nx-set-shas/blob/main/action.yml](https://github.com/nrwl/nx-set-shas/blob/main/action.yml#L44)

**Comment by joh-klein** [comment] 2024-09-13 12:03
Duplicate of #158

**Closed** 2024-09-27 14:28 UTC
